window.currencySymbolMapper = {
    "AUD": "A$",
    "CAD": "CDN$",
    "CNY": "¥",
    "CRC": "₡", 
    "EUR": "€",
    "GBP": "£",
    "HKD": "HK$",
    "ILS": "₪",
    "INR": "₹",
    "JPY": "¥",
    "KRW": "₩",
    "MYR": "RM",
    "NGN": "₦",
    "NZD": "NZ$",
    "PHP": "₱",
    "PLN": "zł",
    "PYG": "₲",
    "SGD": "S$",
    "THB": "฿",
    "TWD": "NT$",
    "UAH": "₴",
    "USD": "$",
    "VND": "₫",
    "ZAR": "R"
};